"""Stable UUID identifiers for postcard detail and share links."""

import json
import sqlite3
import tempfile
import threading
import unittest
import urllib.error
import urllib.request
from pathlib import Path
from unittest.mock import patch
from uuid import UUID, uuid4

from app.db import Database, SCHEMA_VERSION
from app.server import make_server


class UuidTest(unittest.TestCase):
    def setUp(self):
        self.db = Database(":memory:")
        self.addCleanup(self.db.close)

    def create(self):
        return self.db.create({
            "front_image_path": "/images/front.png", "back_image_path": "/images/back.png",
            "place": "Berlin", "region": "Berlin", "year": "1900",
            "description": "Keep this", "tags": ["a", "b"],
        })

    def test_random_unique_stable_and_immutable(self):
        records = [self.create() for _ in range(100)]
        self.assertEqual(len({item["uuid"] for item in records}), 100)
        for item in records:
            self.assertEqual(UUID(item["uuid"]).version, 4)
            self.assertEqual(str(UUID(item["uuid"])), item["uuid"])
            self.assertEqual(self.db.get_by_uuid(item["uuid"]), item)
        item = records[0]
        updated = self.db.update(item["id"], {"place": "Changed"})
        self.assertEqual(updated["uuid"], item["uuid"])
        with self.assertRaisesRegex(ValueError, "cannot be changed"):
            self.db.update(item["id"], {"uuid": str(uuid4())})
        with self.assertRaisesRegex(ValueError, "generated by the server"):
            self.db.create({"front_image_path": "/f.png", "uuid": str(uuid4())})
        self.assertIsNone(self.db.get_by_uuid(str(uuid4())))

    def test_restore_keeps_links_append_generates_new_identifiers(self):
        original = self.create()
        export = self.db.export_data()
        self.assertEqual(export["schema_version"], 4)
        self.db.import_data(export, "replace")
        self.assertEqual(self.db.get_by_uuid(original["uuid"]), original)
        self.db.import_data(export, "append")
        records = self.db.list()
        self.assertEqual(len({item["uuid"] for item in records}), 2)
        for record in records:
            self.assertEqual(
                {k: v for k, v in record.items() if k not in ("id", "uuid")},
                {k: v for k, v in original.items() if k not in ("id", "uuid")},
            )
        for version in (1, 2, 3):
            old = dict(original)
            del old["uuid"]
            self.db.import_data({"schema_version": version, "postcards": [old]}, "replace")
            self.assertEqual(UUID(self.db.list()[0]["uuid"]).version, 4)

    def test_invalid_uuid_and_duplicate_imports_are_atomic(self):
        original = self.create()
        for value in (None, "", "42", original["uuid"].upper(),
                      "b962a358-8899-1000-8999-6973bac5d599"):
            with self.subTest(value=value):
                with self.assertRaisesRegex(ValueError, "UUIDv4"):
                    self.db.get_by_uuid(value)
                for mode in ("append", "replace"):
                    with self.assertRaisesRegex(ValueError, "UUIDv4"):
                        self.db.import_data({"schema_version": 4, "postcards": [
                            dict(original, uuid=value),
                        ]}, mode)
                    self.assertEqual(self.db.list(), [original])
        with self.assertRaisesRegex(ValueError, "include uuid"):
            self.db.import_data({"schema_version": 4, "postcards": [
                {"front_image_path": "/f.png"},
            ]}, "replace")
        duplicate = dict(original, id=original["id"] + 1)
        with self.assertRaisesRegex(ValueError, "postcards.uuid"):
            self.db.import_data({"schema_version": 4, "postcards": [
                original, duplicate,
            ]}, "replace")
        self.assertEqual(self.db.list(), [original])
        self.db.import_data({"schema_version": 4, "postcards": [original, duplicate]}, "append")
        self.assertEqual(len({item["uuid"] for item in self.db.list()}), 3)

    def test_migration_retains_all_data_and_uuid_survives_reopen(self):
        with tempfile.TemporaryDirectory() as root:
            path = Path(root) / "old.db"
            original = self.create()
            # Use the pre-UUID version-3 table, retaining all stored fields.
            with sqlite3.connect(path) as conn:
                conn.execute("""
                    CREATE TABLE postcards (
                        id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, notes TEXT,
                        front_image_path TEXT, back_image_path TEXT, place TEXT,
                        region TEXT, year TEXT, description TEXT, tags TEXT,
                        created_at TEXT, updated_at TEXT)
                """)
                fields = {k: v for k, v in original.items() if k != "uuid"}
                fields["tags"] = json.dumps(fields["tags"])
                conn.execute(
                    f"INSERT INTO postcards ({', '.join(fields)}) "
                    f"VALUES ({', '.join('?' for _ in fields)})", tuple(fields.values()),
                )
                conn.execute("PRAGMA user_version = 3")
            db = Database(path)
            migrated = db.get(original["id"])
            self.assertEqual(
                {k: v for k, v in migrated.items() if k != "uuid"},
                {k: v for k, v in original.items() if k != "uuid"},
            )
            self.assertEqual(UUID(migrated["uuid"]).version, 4)
            db.close()
            reopened = Database(path)
            self.addCleanup(reopened.close)
            self.assertEqual(reopened.get_by_uuid(migrated["uuid"]), migrated)
            with sqlite3.connect(path) as conn:
                self.assertEqual(conn.execute("PRAGMA user_version").fetchone()[0], SCHEMA_VERSION)
                with self.assertRaises(sqlite3.IntegrityError):
                    conn.execute("UPDATE postcards SET uuid = ?", (None,))

    def test_failed_uuid_migration_rolls_back(self):
        with tempfile.TemporaryDirectory() as root:
            path = Path(root) / "old.db"
            with sqlite3.connect(path) as conn:
                conn.executescript("""
                    CREATE TABLE postcards (id INTEGER PRIMARY KEY, title TEXT, notes TEXT,
                        created_at TEXT, updated_at TEXT);
                    INSERT INTO postcards VALUES (1, 'A', '', 'c', 'u');
                    INSERT INTO postcards VALUES (2, 'B', '', 'c', 'u');
                    PRAGMA user_version = 1;
                """)
            with patch("app.db.uuid4", return_value=UUID("b962a358-8899-4000-8999-6973bac5d599")):
                with self.assertRaises(sqlite3.IntegrityError):
                    Database(path)
            with sqlite3.connect(path) as conn:
                self.assertEqual(conn.execute("PRAGMA user_version").fetchone()[0], 1)
                self.assertNotIn("uuid", [row[1] for row in conn.execute("PRAGMA table_info(postcards)")])
                self.assertEqual(conn.execute("SELECT count(*) FROM postcards").fetchone()[0], 2)


class UuidApiTest(unittest.TestCase):
    def test_uuid_lookup_and_internal_numeric_editing(self):
        with tempfile.TemporaryDirectory() as root:
            server = make_server("127.0.0.1", 0, str(Path(root) / "test.db"))
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            base = f"http://127.0.0.1:{server.server_address[1]}"

            def request(path, method="GET", data=None):
                req = urllib.request.Request(
                    base + path, method=method,
                    data=json.dumps(data).encode() if data is not None else None,
                    headers={"Content-Type": "application/json"},
                )
                try:
                    with urllib.request.urlopen(req) as response:
                        return response.status, json.loads(response.read())
                except urllib.error.HTTPError as error:
                    with error:
                        return error.code, json.loads(error.read())

            try:
                status, postcard = request("/api/postcards", "POST", {"front_image_path": "/f.png"})
                self.assertEqual(status, 201)
                path = f"/api/postcards/by-uuid/{postcard['uuid']}"
                self.assertEqual(request(path), (200, postcard))
                self.assertEqual(request("/api/postcards/by-uuid/42")[0], 400)
                self.assertEqual(request(f"/api/postcards/by-uuid/{uuid4()}")[0], 404)
                status, updated = request(f"/api/postcards/{postcard['id']}", "PUT", {"place": "X"})
                self.assertEqual((status, updated["uuid"]), (200, postcard["uuid"]))
                self.assertEqual(request(path)[1]["place"], "X")
            finally:
                server.shutdown()
                server.server_close()
                server.RequestHandlerClass.db.close()
                thread.join()
